name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: dolfinx/real

    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cd lib/src && cmake .
    - name: make
      run: cd lib/src && make
      